version: '3.5'

services:
    postgres:
        container_name: dpgnetwork
        image: postgres:latest
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "23456:5432"